import { CollectionConfig } from 'payload'

export const LaboratoryGrownDiamonds: CollectionConfig = {
  slug: 'laboratory-grown-diamonds',
  admin: {
    useAsTitle: 'diamond_id',
  },
  access: {
    read: () => true,
  },
  fields: [
    { name: 'diamond_id', label: 'Diamond ID', type: 'text', required: true, unique: true },
    { name: 'stock_id', label: 'Stock ID', type: 'text', required: true },
    { name: 'ReportNo', label: 'Report No', type: 'text', required: true },
    { name: 'shape', label: 'Shape', type: 'text' },
    { name: 'fullShape', label: 'Full Shape', type: 'text' },
    { name: 'carats', label: 'Carats', type: 'number' },
    { name: 'color', label: 'Color', type: 'text' },
    { name: 'clarity', label: 'Clarity', type: 'text' },
    { name: 'cut', label: 'Cut', type: 'text' },
    { name: 'polish', label: 'Polish', type: 'text' },
    { name: 'symmetry', label: 'Symmetry', type: 'text' },
    { name: 'fluorescence', label: 'Fluorescence', type: 'text' },
    { name: 'fluorescenceColor', label: 'Fluorescence Color', type: 'text' },
    { name: 'eyeClean', label: 'Eye Clean', type: 'text' },
    { name: 'brown', label: 'Brown', type: 'text' },
    { name: 'green', label: 'Green', type: 'text' },
    { name: 'milky', label: 'Milky', type: 'text' },
    { name: 'length', label: 'Length (mm)', type: 'number' },
    { name: 'width', label: 'Width (mm)', type: 'number' },
    { name: 'height', label: 'Height (mm)', type: 'number' },
    { name: 'depth', label: 'Depth (%)', type: 'number' },
    { name: 'table', label: 'Table (%)', type: 'number' },
    { name: 'culet', label: 'Culet', type: 'text' },
    { name: 'girdle', label: 'Girdle', type: 'text' },
    { name: 'starLength', label: 'Star Length (%)', type: 'number' },
    { name: 'lowerGirdle', label: 'Lower Girdle (%)', type: 'number' },
    { name: 'crownHeight', label: 'Crown Height (%)', type: 'number' },
    { name: 'crownAngle', label: 'Crown Angle (°)', type: 'number' },
    { name: 'pavilionAngle', label: 'Pavilion Angle (°)', type: 'number' },
    { name: 'pavilionHeight', label: 'Pavilion Height (%)', type: 'number' },
    { name: 'pavilionDepth', label: 'Pavilion Depth (%)', type: 'number' },
    { name: 'discount', label: 'Discount', type: 'text' },
    { name: 'price', label: 'Price (USD)', type: 'number' },
    { name: 'markup_price', label: 'Markup Price', type: 'number' },
    { name: 'markup_currency', label: 'Markup Currency', type: 'text' },
    { name: 'price_per_carat', label: 'Price per Carat', type: 'number' },
    { name: 'deliveredPrice', label: 'Delivered Price', type: 'number' },
    { name: 'lab', label: 'Lab', type: 'text' },
    { name: 'pdf', label: 'PDF', type: 'text' },
    { name: 'video', label: 'Video', type: 'text' },
    { name: 'image', label: 'Image', type: 'text' },
    { name: 'videosImageUri', label: 'Video Preview Image', type: 'text' },
    { name: 'videosFrame', label: 'Video Frame', type: 'number' },
    { name: 'blue', label: 'Blue', type: 'number' },
    { name: 'gray', label: 'Gray', type: 'number' },
    { name: 'minDeliveryDays', label: 'Min Delivery Days', type: 'number' },
    { name: 'maxDeliveryDays', label: 'Max Delivery Days', type: 'number' },
    { name: 'country', label: 'Country', type: 'text' },
    { name: 'mine_of_origin', label: 'Mine of Origin', type: 'text' },
    {
      name: 'canada_mark_eligible',
      label: 'CanadaMark Eligible',
      type: 'checkbox',
      defaultValue: false,
    },
    { name: 'is_returnable', label: 'Is Returnable', type: 'checkbox', defaultValue: false },
    { name: 'is_diavaia', label: 'Is Diavaia', type: 'checkbox', defaultValue: false },
    { name: 'published', label: 'Published', type: 'checkbox', defaultValue: true },
  ],
}
