/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    orders: Order;
    'natural-diamonds': NaturalDiamond;
    'natural-colored-diamonds': NaturalColoredDiamond;
    'laboratory-grown-diamonds': LaboratoryGrownDiamond;
    'laboratory-grown-colored-diamonds': LaboratoryGrownColoredDiamond;
    Jewelleries: Jewellery;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'natural-diamonds': NaturalDiamondsSelect<false> | NaturalDiamondsSelect<true>;
    'natural-colored-diamonds': NaturalColoredDiamondsSelect<false> | NaturalColoredDiamondsSelect<true>;
    'laboratory-grown-diamonds': LaboratoryGrownDiamondsSelect<false> | LaboratoryGrownDiamondsSelect<true>;
    'laboratory-grown-colored-diamonds': LaboratoryGrownColoredDiamondsSelect<false> | LaboratoryGrownColoredDiamondsSelect<true>;
    Jewelleries: JewelleriesSelect<false> | JewelleriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  civility: 'mx' | 'mr' | 'mrs' | 'ms';
  firstName: string;
  lastName: string;
  country:
    | 'AF'
    | 'AX'
    | 'AL'
    | 'DZ'
    | 'AS'
    | 'AD'
    | 'AO'
    | 'AI'
    | 'AQ'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AW'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BM'
    | 'BT'
    | 'BO'
    | 'BA'
    | 'BW'
    | 'BV'
    | 'BR'
    | 'IO'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'CV'
    | 'KY'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CX'
    | 'CC'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CK'
    | 'CR'
    | 'CI'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'ET'
    | 'FK'
    | 'FO'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GF'
    | 'PF'
    | 'TF'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GI'
    | 'GR'
    | 'GL'
    | 'GD'
    | 'GP'
    | 'GU'
    | 'GT'
    | 'GG'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HM'
    | 'VA'
    | 'HN'
    | 'HK'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IM'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JE'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MO'
    | 'MK'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MQ'
    | 'MR'
    | 'MU'
    | 'YT'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'MS'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'AN'
    | 'NC'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'NU'
    | 'NF'
    | 'MP'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PS'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PN'
    | 'PL'
    | 'PT'
    | 'PR'
    | 'QA'
    | 'RE'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'SH'
    | 'KN'
    | 'LC'
    | 'PM'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'CS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'GS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SJ'
    | 'SZ'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TW'
    | 'TJ'
    | 'TZ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TK'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TC'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UM'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'VG'
    | 'VI'
    | 'WF'
    | 'EH'
    | 'YE'
    | 'ZM'
    | 'ZW';
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  order_id: string;
  status: string;
  email: string;
  amounts: number;
  biling_informations: {
    address: string;
    address_2?: string | null;
    first_name: string;
    last_name: string;
    country: string;
    provinces: string;
    city: string;
    zip_code: string;
    phone: string;
  };
  carts?:
    | {
        product_id: string;
        title: string;
        color: string;
        cut: string;
        clarity: string;
        price: string;
        imageUrl: string;
        max_delivery_days: number;
        type: string;
        lab: string;
        hsCode?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "natural-diamonds".
 */
export interface NaturalDiamond {
  id: string;
  stock_id: string;
  report_no: string;
  shape?: string | null;
  full_shape?: string | null;
  carats?: number | null;
  col?: string | null;
  clar?: string | null;
  cut?: string | null;
  pol?: string | null;
  symm?: string | null;
  flo?: string | null;
  flo_col?: string | null;
  eye_clean?: string | null;
  brown?: string | null;
  green?: string | null;
  milky?: string | null;
  fancy_color?: string | null;
  fancy_overtone?: string | null;
  fancy_intensity?: string | null;
  color_shade?: string | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  table?: number | null;
  culet?: string | null;
  girdle?: string | null;
  star_length?: number | null;
  lower_girdle?: number | null;
  crown_height?: number | null;
  crown_angle?: number | null;
  pav_angle?: number | null;
  pav_height?: number | null;
  pav_depth?: number | null;
  discount?: string | null;
  price?: number | null;
  markup_price?: number | null;
  markup_currency?: string | null;
  price_per_carat?: number | null;
  delivered_price?: number | null;
  lab?: string | null;
  pdf?: string | null;
  video?: string | null;
  image?: string | null;
  videos_image_uri?: string | null;
  videos_frame?: number | null;
  blue?: string | null;
  gray?: string | null;
  min_delivery_days?: number | null;
  max_delivery_days?: number | null;
  country?: string | null;
  mine_of_origin?: string | null;
  canada_mark_eligible?: boolean | null;
  labgrown_type?: string | null;
  lg?: string | null;
  is_returnable?: boolean | null;
  is_diavaia?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "natural-colored-diamonds".
 */
export interface NaturalColoredDiamond {
  id: string;
  stock_id: string;
  report_no: string;
  shape?: string | null;
  full_shape?: string | null;
  carats?: number | null;
  col?: string | null;
  clar?: string | null;
  cut?: string | null;
  pol?: string | null;
  symm?: string | null;
  flo?: string | null;
  flo_col?: string | null;
  eye_clean?: string | null;
  brown?: string | null;
  green?: string | null;
  milky?: string | null;
  fancy_color?: string | null;
  fancy_overtone?: string | null;
  fancy_intensity?: string | null;
  color_shade?: string | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  table?: number | null;
  culet?: string | null;
  girdle?: string | null;
  star_length?: number | null;
  lower_girdle?: number | null;
  crown_height?: number | null;
  crown_angle?: number | null;
  pav_angle?: number | null;
  pav_height?: number | null;
  pav_depth?: number | null;
  discount?: string | null;
  price?: number | null;
  markup_price?: number | null;
  markup_currency?: string | null;
  price_per_carat?: number | null;
  delivered_price?: number | null;
  lab?: string | null;
  pdf?: string | null;
  video?: string | null;
  image?: string | null;
  videos_image_uri?: string | null;
  videos_frame?: number | null;
  blue?: string | null;
  gray?: string | null;
  min_delivery_days?: number | null;
  max_delivery_days?: number | null;
  country?: string | null;
  mine_of_origin?: string | null;
  canada_mark_eligible?: boolean | null;
  labgrown_type?: string | null;
  lg?: string | null;
  is_returnable?: boolean | null;
  is_diavaia?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laboratory-grown-diamonds".
 */
export interface LaboratoryGrownDiamond {
  id: string;
  stock_id: string;
  report_no: string;
  shape?: string | null;
  full_shape?: string | null;
  aset?: string | null;
  aset_link?: string | null;
  carats?: number | null;
  col?: string | null;
  clar?: string | null;
  cut?: string | null;
  pol?: string | null;
  symm?: string | null;
  flo?: string | null;
  flo_col?: string | null;
  eye_clean?: string | null;
  brown?: string | null;
  green?: string | null;
  milky?: string | null;
  fancy_color?: string | null;
  fancy_overtone?: string | null;
  fancy_intensity?: string | null;
  color_shade?: string | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  table?: number | null;
  culet?: string | null;
  girdle?: string | null;
  star_length?: number | null;
  lower_girdle?: number | null;
  crown_height?: number | null;
  crown_angle?: number | null;
  pav_angle?: number | null;
  pav_height?: number | null;
  pav_depth?: number | null;
  discount?: string | null;
  price?: number | null;
  markup_price?: number | null;
  markup_currency?: string | null;
  price_per_carat?: number | null;
  delivered_price?: number | null;
  lab?: string | null;
  pdf?: string | null;
  video?: string | null;
  image?: string | null;
  videos_image_uri?: string | null;
  videos_frame?: number | null;
  blue?: string | null;
  gray?: string | null;
  min_delivery_days?: number | null;
  max_delivery_days?: number | null;
  country?: string | null;
  mine_of_origin?: string | null;
  canada_mark_eligible?: boolean | null;
  labgrown_type?: string | null;
  lg?: string | null;
  is_returnable?: boolean | null;
  is_diavaia?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laboratory-grown-colored-diamonds".
 */
export interface LaboratoryGrownColoredDiamond {
  id: string;
  stock_id: string;
  report_no: string;
  shape?: string | null;
  full_shape?: string | null;
  carats?: number | null;
  col?: string | null;
  clar?: string | null;
  cut?: string | null;
  pol?: string | null;
  symm?: string | null;
  flo?: string | null;
  flo_col?: string | null;
  eye_clean?: string | null;
  brown?: string | null;
  green?: string | null;
  milky?: string | null;
  fancy_color?: string | null;
  fancy_overtone?: string | null;
  fancy_intensity?: string | null;
  color_shade?: string | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  table?: number | null;
  culet?: string | null;
  girdle?: string | null;
  star_length?: number | null;
  lower_girdle?: number | null;
  crown_height?: number | null;
  crown_angle?: number | null;
  pav_angle?: number | null;
  pav_height?: number | null;
  pav_depth?: number | null;
  discount?: string | null;
  price?: number | null;
  markup_price?: number | null;
  markup_currency?: string | null;
  price_per_carat?: number | null;
  delivered_price?: number | null;
  lab?: string | null;
  pdf?: string | null;
  video?: string | null;
  image?: string | null;
  videos_image_uri?: string | null;
  videos_frame?: number | null;
  blue?: string | null;
  gray?: string | null;
  min_delivery_days?: number | null;
  max_delivery_days?: number | null;
  country?: string | null;
  mine_of_origin?: string | null;
  canada_mark_eligible?: boolean | null;
  labgrown_type?: string | null;
  lg?: string | null;
  is_returnable?: boolean | null;
  is_diavaia?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Jewelleries".
 */
export interface Jewellery {
  id: string;
  ref_diavaia: string;
  product_type?: ('Earring' | 'Bracelet' | 'Necklace') | null;
  metal_type?: string | null;
  total_stones?: number | null;
  stone_type?: string | null;
  stone_colour?: string | null;
  stone_clarity?: string | null;
  weight?: number | null;
  ctw?: number | null;
  retail_price?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'natural-diamonds';
        value: string | NaturalDiamond;
      } | null)
    | ({
        relationTo: 'natural-colored-diamonds';
        value: string | NaturalColoredDiamond;
      } | null)
    | ({
        relationTo: 'laboratory-grown-diamonds';
        value: string | LaboratoryGrownDiamond;
      } | null)
    | ({
        relationTo: 'laboratory-grown-colored-diamonds';
        value: string | LaboratoryGrownColoredDiamond;
      } | null)
    | ({
        relationTo: 'Jewelleries';
        value: string | Jewellery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  civility?: T;
  firstName?: T;
  lastName?: T;
  country?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  order_id?: T;
  status?: T;
  email?: T;
  amounts?: T;
  biling_informations?:
    | T
    | {
        address?: T;
        address_2?: T;
        first_name?: T;
        last_name?: T;
        country?: T;
        provinces?: T;
        city?: T;
        zip_code?: T;
        phone?: T;
      };
  carts?:
    | T
    | {
        product_id?: T;
        title?: T;
        color?: T;
        cut?: T;
        clarity?: T;
        price?: T;
        imageUrl?: T;
        max_delivery_days?: T;
        type?: T;
        lab?: T;
        hsCode?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "natural-diamonds_select".
 */
export interface NaturalDiamondsSelect<T extends boolean = true> {
  stock_id?: T;
  report_no?: T;
  shape?: T;
  full_shape?: T;
  carats?: T;
  col?: T;
  clar?: T;
  cut?: T;
  pol?: T;
  symm?: T;
  flo?: T;
  flo_col?: T;
  eye_clean?: T;
  brown?: T;
  green?: T;
  milky?: T;
  fancy_color?: T;
  fancy_overtone?: T;
  fancy_intensity?: T;
  color_shade?: T;
  length?: T;
  width?: T;
  height?: T;
  depth?: T;
  table?: T;
  culet?: T;
  girdle?: T;
  star_length?: T;
  lower_girdle?: T;
  crown_height?: T;
  crown_angle?: T;
  pav_angle?: T;
  pav_height?: T;
  pav_depth?: T;
  discount?: T;
  price?: T;
  markup_price?: T;
  markup_currency?: T;
  price_per_carat?: T;
  delivered_price?: T;
  lab?: T;
  pdf?: T;
  video?: T;
  image?: T;
  videos_image_uri?: T;
  videos_frame?: T;
  blue?: T;
  gray?: T;
  min_delivery_days?: T;
  max_delivery_days?: T;
  country?: T;
  mine_of_origin?: T;
  canada_mark_eligible?: T;
  labgrown_type?: T;
  lg?: T;
  is_returnable?: T;
  is_diavaia?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "natural-colored-diamonds_select".
 */
export interface NaturalColoredDiamondsSelect<T extends boolean = true> {
  stock_id?: T;
  report_no?: T;
  shape?: T;
  full_shape?: T;
  carats?: T;
  col?: T;
  clar?: T;
  cut?: T;
  pol?: T;
  symm?: T;
  flo?: T;
  flo_col?: T;
  eye_clean?: T;
  brown?: T;
  green?: T;
  milky?: T;
  fancy_color?: T;
  fancy_overtone?: T;
  fancy_intensity?: T;
  color_shade?: T;
  length?: T;
  width?: T;
  height?: T;
  depth?: T;
  table?: T;
  culet?: T;
  girdle?: T;
  star_length?: T;
  lower_girdle?: T;
  crown_height?: T;
  crown_angle?: T;
  pav_angle?: T;
  pav_height?: T;
  pav_depth?: T;
  discount?: T;
  price?: T;
  markup_price?: T;
  markup_currency?: T;
  price_per_carat?: T;
  delivered_price?: T;
  lab?: T;
  pdf?: T;
  video?: T;
  image?: T;
  videos_image_uri?: T;
  videos_frame?: T;
  blue?: T;
  gray?: T;
  min_delivery_days?: T;
  max_delivery_days?: T;
  country?: T;
  mine_of_origin?: T;
  canada_mark_eligible?: T;
  labgrown_type?: T;
  lg?: T;
  is_returnable?: T;
  is_diavaia?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laboratory-grown-diamonds_select".
 */
export interface LaboratoryGrownDiamondsSelect<T extends boolean = true> {
  stock_id?: T;
  report_no?: T;
  shape?: T;
  full_shape?: T;
  aset?: T;
  aset_link?: T;
  carats?: T;
  col?: T;
  clar?: T;
  cut?: T;
  pol?: T;
  symm?: T;
  flo?: T;
  flo_col?: T;
  eye_clean?: T;
  brown?: T;
  green?: T;
  milky?: T;
  fancy_color?: T;
  fancy_overtone?: T;
  fancy_intensity?: T;
  color_shade?: T;
  length?: T;
  width?: T;
  height?: T;
  depth?: T;
  table?: T;
  culet?: T;
  girdle?: T;
  star_length?: T;
  lower_girdle?: T;
  crown_height?: T;
  crown_angle?: T;
  pav_angle?: T;
  pav_height?: T;
  pav_depth?: T;
  discount?: T;
  price?: T;
  markup_price?: T;
  markup_currency?: T;
  price_per_carat?: T;
  delivered_price?: T;
  lab?: T;
  pdf?: T;
  video?: T;
  image?: T;
  videos_image_uri?: T;
  videos_frame?: T;
  blue?: T;
  gray?: T;
  min_delivery_days?: T;
  max_delivery_days?: T;
  country?: T;
  mine_of_origin?: T;
  canada_mark_eligible?: T;
  labgrown_type?: T;
  lg?: T;
  is_returnable?: T;
  is_diavaia?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laboratory-grown-colored-diamonds_select".
 */
export interface LaboratoryGrownColoredDiamondsSelect<T extends boolean = true> {
  stock_id?: T;
  report_no?: T;
  shape?: T;
  full_shape?: T;
  carats?: T;
  col?: T;
  clar?: T;
  cut?: T;
  pol?: T;
  symm?: T;
  flo?: T;
  flo_col?: T;
  eye_clean?: T;
  brown?: T;
  green?: T;
  milky?: T;
  fancy_color?: T;
  fancy_overtone?: T;
  fancy_intensity?: T;
  color_shade?: T;
  length?: T;
  width?: T;
  height?: T;
  depth?: T;
  table?: T;
  culet?: T;
  girdle?: T;
  star_length?: T;
  lower_girdle?: T;
  crown_height?: T;
  crown_angle?: T;
  pav_angle?: T;
  pav_height?: T;
  pav_depth?: T;
  discount?: T;
  price?: T;
  markup_price?: T;
  markup_currency?: T;
  price_per_carat?: T;
  delivered_price?: T;
  lab?: T;
  pdf?: T;
  video?: T;
  image?: T;
  videos_image_uri?: T;
  videos_frame?: T;
  blue?: T;
  gray?: T;
  min_delivery_days?: T;
  max_delivery_days?: T;
  country?: T;
  mine_of_origin?: T;
  canada_mark_eligible?: T;
  labgrown_type?: T;
  lg?: T;
  is_returnable?: T;
  is_diavaia?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Jewelleries_select".
 */
export interface JewelleriesSelect<T extends boolean = true> {
  ref_diavaia?: T;
  product_type?: T;
  metal_type?: T;
  total_stones?: T;
  stone_type?: T;
  stone_colour?: T;
  stone_clarity?: T;
  weight?: T;
  ctw?: T;
  retail_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}